name: Haskell CI

on:
  push:
    branches: '*'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc-version: ['8.10', '9.0', '9.2']

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc-version }}
        cabal-version: '3.2'

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-${{ matrix.ghc-version }}--build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc-version }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-${{ matrix.ghc-version }}-build-
          ${{ runner.os }}-${{ matrix.ghc-version }}

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks all
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: cabal test all --test-show-details=direct
