name: Haskell CI

on:
  push:
    branches: '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc-version: ['8.10', '9.0', '9.2']

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v2
      id: setup-haskell
      with:
        ghc-version: ${{ matrix.ghc-version }}
        cabal-version: '3.6'

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc-version }}--build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc-version }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-${{ matrix.ghc-version }}-build-
          ${{ runner.os }}-${{ matrix.ghc-version }}

    - name: Install dependencies
      run: |
        cabal update
        cabal new-build --only-dependencies --enable-tests --enable-benchmarks all
    - name: Build
      run: cabal new-build --enable-tests --enable-benchmarks all
    - name: test
      run: cabal new-test --test-show-details=direct all
    - name: Install markdown-unlit
      run: cabal install markdown-unlit
    - name: Build README
      run: cabal v2-exec ghc -- -pgmL markdown-unlit README.lhs
    - name: Run README
      run: ./README
